import { EventEmitter } from 'events';

export const EventBus = new EventEmitter();

// Define standard events
export enum SystemEvents {
    MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
    ROUTING_COMPLETE = 'ROUTING_COMPLETE',
    RESEARCH_STARTED = 'RESEARCH_STARTED',
    RESEARCH_COMPLETE = 'RESEARCH_COMPLETE',
    PLANNING_STARTED = 'PLANNING_STARTED',
    PLANNING_COMPLETE = 'PLANNING_COMPLETE',
    STEP_EXECUTION_START = 'STEP_EXECUTION_START',
    STEP_EXECUTION_COMPLETE = 'STEP_EXECUTION_COMPLETE',
    COMPOSING_STARTED = 'COMPOSING_STARTED',
    PIPELINE_COMPLETE = 'PIPELINE_COMPLETE',
    PIPELINE_ERROR = 'PIPELINE_ERROR',
    ARTIFACT_CREATED = 'ARTIFACT_CREATED',
    ARTIFACT_UPDATED = 'ARTIFACT_UPDATED'
}

